<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StaticController extends Controller
{
    public function index($locale = 'es')
    {

        if (!in_array($locale, ['en', 'es'])) $locale = 'es';

        $lang = [
            'en' => array(
                "titulo" => "Event Management Software",
                "bajada" => "Powerful, simple, adaptable. ",
                "logo" => "Sistema Multilenguaje",
                "cambiar_idioma" => "Lenguaje",
                "cambiar" => "Change",
                "opcion_1" => "Language",
                "opcion_2" => "Spanish",
                "opcion_3" => "English",
                "descripcion" => "When it comes to quality and customer focus, we believe we can help and provide the best experiences.",
                "home" => "Home",
                "nosotros" => "About Us",
                "servicios" => "Services",
                "plataforma" => "Platform",
                "contacto" => "Contact Us",
                "qhacemos" => "What we do",
                "qteofrecemos" => "What we offer you",
                "conversemos" => "Let’s talk",
                "qs" => "About Us",
                "bajadaqs" => "Venoot.com is a complete platform responsible for simplifying the logistics, analytics and the event management processes.",
                "descqs" => "We are a digital service platform to transform the process of organizing corporate, technological, cultural, sports events and entertainment activities in general, in a comfortable, easy, fast and safe service.",
                "gestiona" => "Management",
                "bgestiona" => "In our set of marketing and customer management tools , it’s all based on a system where the tools we put at your disposal are powerful when used together.",
                "comunica" => "Communication",
                "bcomunica" => "We know how challenging it is to plan events, especially when your goal is to generate quality experiences, so we provide a dynamic, flexible and easy to use tool for the communication and marketing of your events.",
                "seguimiento" => "Follow-up",
                "bseguimiento" => "Our system uses the information of the client to deliver a traceability, interaction and multichannel analysis, for the subsequent detailed analysis of your clients’ behavior with your events.",
                "analitica" => "Analytics",
                "banalitica" => "Customer analytics allows businesses to grow, therefore, you can create personalized experiences that will allow you to generate sales, increase participation and win the loyalty of the customers attending your events.",
                "servicios" => "Our Services",
                "bservicios" => "Improve our clients’ experience!",
                "mservicios" => "The Venoot.com platform gives you the absolute autonomy to plan and manage events without having to depend on other platforms to manage any of the steps before or after your events.",
                "s1" => "Online Registration and QR Tickets",
                "bs1" => "Our event platform is fully integrated with a complete registration and attendance confirmation or ticket sales module.",
                "s2" => "Discount Coupons",
                "bs2" => "Create your discount access coupons created by Venoot.com or your customer database, or any discount with a department store or bank, through our API connectivity module.",
                "s3" => "Attendance List Management",
                "bs3" => "Easily import a guest list from your source file, expand it by uploading other contacts, as simple as that!",
                "s4" => "Surveys Publication",
                "bs4" => "Design, configure, segment and post, it's that easy.",
                "s5" => "UI/UX Design",
                "bs5" => "The structure of the code is totally responsive, make sure that the websites of your events work well on a variety of devices and screen sizes.",
                "s6" => "Payment Platform",
                "bs6" => "In a matter of minutes sell through our platform, just select this option and you're done!",
                "s7" => "eMails",
                "bs7" => "Our event management platform integrates a powerful email generator that will allow you to send guaranteed emails.",
                "s8" => "Attendees Registry and Tracking",
                "bs8" => "Our check-in application generates the necessary traces to verify the routes that attendees take to your events.",
                "s9" => "Creation of the Event’s Agenda",
                "bs9" => "Days and activities of your event, you can link it with your speakers, with your Check-in APP, with APP4MEETING, in other words, we develop business intelligence",
                "s10" => "Event Control Dashboard",
                "bs10" => "Get the statistics you need from the performance of your activities, web, rrss, mails, app, accounts, all in one place.",
                "s11" => "App4Meeting",
                "bs11" => "A new Venoot.com service, APP for events, focus on the competition and give your customers the APP they deserve.",
                "s12" => "Customized Forms",
                "bs12" => "Post events confirmation forms with the information you want, totally free.",
                "s13" => "Website for your Event",
                "bs13" => "Create a responsive web page, without any programming knowledge in just a matter of minutes.",
                "s14" => "24/7/365",
                "bs14" => "Our platform updates all the actions that happen with the event website or emails, you can access and download the reports whenever you want.",
                "s15" => "eMails Design",
                "bs15" => "With our Drag & Drop emails you can design your invitation templates or import your own html designs for shipments.",
                "s16" => "Work with your Cell Phone",
                "bs16" => "Easily manage check-in with our application and verify the route and times of your attendees at your events. ",
                "s17" => "Design your Venues",
                "bs17" => "Upload the image of your venue, draw the areas and determine the amount of spaces available for sales or access confirmation.",
                "s18" => "Schedule your Mailings",
                "bs18" => "Schedule your mailings for a desired time and date, very useful for those moments in which we cannot be connected. ",
                "s19" => "Adwords",
                "bs19" => "We invest in your brand in the best showcase of the moment.",
                "s20" => "Community Manager",
                "bs20" => "We manage your content in our positioning network to contribute to your demand generation campaigns.",
                "plataforma-venoot" => "Some events that have already been published through our system.",
                "clientes" => "Our Clients",
                "morethan" => "More than",
                "enviados" => "eMails sent",
                "check" => "Participants’ Check-in",
                "usuarios" => "Average connected users",
                "bcontacto" => "Send us your info or call us so that we can assist you and offer you quality advice!",
                "derechos" => "All rights reserved.",
                "contactosend" => "I want to be contacted",
                "nombre" => "Enter your name",
                "email" => "Enter your email address",
                "valido" => "Enter a valid data",
                "loginuser" => "Login Users",
                "loginparticipant" => "Login Participants",
            ),

            'es' => array(
                "titulo" => "Software de Gestión de Eventos",
                "bajada" => "Potente, simple, adaptable.",
                "logo" => "Sistema Multilenguaje",
                "cambiar_idioma" => "Lenguaje",
                "cambiar" => "Cambiar",
                "opcion_1" => "Idioma",
                "opcion_2" => "Español",
                "opcion_3" => "Inglés",
                "descripcion" => "Cuando se trata de calidad y foco en el cliente, creemos que podemos ayudar y brindar las mejores experiencias.",
                "home" => "Home",
                "nosotros" => "Nosotros",
                "servicios" => "Servicios",
                "plataforma" => "Plataforma",
                "contacto" => "Contacto",
                "qhacemos" => "que hacemos",
                "qteofrecemos" => "que te ofrecemos",
                "conversemos" => "conversemos",
                "qs" => "Quienes Somos",
                "bajadaqs" => "Venoot.com es una completa plataforma que se encarga de simplificar los procesos logísticos, analítica y gestión de eventos.",
                "descqs" => "Somos una plataforma de servicio digital para transformar el proceso de organización de eventos corporativos, tecnológicos, culturales, deportivos y actividades de entretenimiento en general, en un servicio cómodo, fácil, rápido y seguro.",
                "gestiona" => "Gestiona",
                "bgestiona" => "En nuestra suite de herramientas para marketing y gestión de clientes, esta todo basado en un sistema donde las herramientas que ponemos a tu disposición son poderosas cuando se usan en conjunto.",
                "comunica" => "Comunica",
                "bcomunica" => "Sabemos lo desafiante que es planificar eventos, especialmente cuando tu objetivo es generar experiencias de calidad, por eso proporcionamos una herramienta dinámica, flexible y fácil de usar para la comunicación y la comercialización de tus eventos.",
                "seguimiento" => "Seguimiento",
                "bseguimiento" => "Nuestro sistema utiliza la información del cliente para entregar una trazabilidad, interacción y análisis multicanal, para el posterior analisis de forma detallada el comportamiento de los clientes con tus eventos.",
                "analitica" => "Analítica",
                "banalitica" => "La analítica de clientes permite hacer crecer los negocios, de esta manera se puede crear experiencias personalizadas que le permitirán generar ventas, participación y fidelidad por parte de los consumidores de tus eventos.",
                "servicios" => "Nuestros Servicios",
                "bservicios" => "Mejorar la experiencia de nuestros clientes!",
                "mservicios" => "La plataforma Venoot.com te entrega la autonomía absoluta para planificar y administrar eventos sin necesidad de depender de otras plataformas para gestionar ninguno de los pasos previos o posteriores a tus eventos. ",
                "s1" => "Registro Online y Tickets QR",
                "bs1" => "Nuestra plataforma de eventos está totalmente integrada con un módulo completo de registro y confirmación de asistencia o venta de entradas tu decides.",
                "s2" => "Cupones de Descuento",
                "bs2" => "Crea tus cupones de acceso con descuento, creados por Venoot.com o con tu BBDD de clientes o algún descuento con alguna casa comercial o banco mediante nuestro módulo de conectividad API.",
                "s3" => "Gestión de Lista de Invitados",
                "bs3" => "Importa fácilmente una lista de invitados desde tu archivo de origen, amplíala subiéndo otros contactos así de simple.",
                "s4" => "Publicación de Encuestas",
                "bs4" => "Diseña, configura, segmenta y publica, así de fácil.",
                "s5" => "UI/UX Design",
                "bs5" => "La estructura del código es totalmente responsive, asegúrate de que los sitios web de tus eventos funcionen bien en una variedad de dispositivos y tamaños de pantallas.",
                "s6" => "Plataforma de Pagos",
                "bs6" => "En cuestión de minutos, vende mediante nuestra plataforma solo selecciona esta opción y ya está!!",
                "s7" => "Envíos de eMails",
                "bs7" => "Nuestra plataforma para gestión de eventos integra un motor de correos potente vía AMAZON que te va a permitir enviar correos electrónicos garantizados.",
                "s8" => "Registro y Tracking de Asistentes",
                "bs8" => "Nuestra aplicación de check-in genera los rastros necesarios para verificar las rutas que realizan los asistentes a tus eventos.",
                "s9" => "Creación de Agenda del Evento",
                "bs9" => "Días y actividades de tu evento, puedes vincularlo con tus speakers, con tu APP de Check-in, con APP4MEETING, o sea, ayudando a la inteligencia del negocio.",
                "s10" => "Dashboard de Control de Eventos",
                "bs10" => "Obtén las estadísticas que necesitas del comportamiento de tus actividades, web, rrss, mails, app, encuentas, tódo en un sólo lugar.",
                "s11" => "App4Meeting",
                "bs11" => "Un nuevo servicio de Venoot.com, APP para eventos, destácate por sobre la competencia y entregales a tus clientes la APP que se merecen.",
                "s12" => "Formularios Personalizados",
                "bs12" => "Publica formularios de confirmación a eventos con la información que estimes, totalmente gratis.",
                "s13" => "Página Web para tu Evento",
                "bs13" => "Cree una página de web receptiva, sin ningún conocimiento de programación tan sólo en cuestión de minutos.",
                "s14" => "Monitorea 24/7/365",
                "bs14" => "Nuestra plataforma actualiza online toda las acciones que sucedan con la web del evento o de los envíos de emails, podrás acceder y descargar los informes al momento que quieras.",
                "s15" => "Diseño de eMails",
                "bs15" => "Con nuestro Drag & Drop de emails podrás diseñar tus plantillas de invitación o importar tus propios diseños html para los envíos.",
                "s16" => "Acredita con tu Celular",
                "bs16" => "Gestiona facilmente el check-in con nuestra aplicación y verifica la ruta y tiempos de tus asistentes en tus eventos.",
                "s17" => "Diseña tus Recintos",
                "bs17" => "Sube la imagen de tu recinto, dibuja las zonas y configura la cantidad de espacios disponibles para ventas o confirmación de accesos.",
                "s18" => "Programa tus envíos",
                "bs18" => "Agenda tus envíos de correos para hora y fecha deseada, muy útil para esos momentos en los cuales no podemos estar conectados.",
                "s19" => "Adwords",
                "bs19" => "Invertimos en tu marca en la mejor vitrina del momento.",
                "s20" => "Community Manager",
                "bs20" => "Gestionamos en nuestra red de posicionamiento tus contenidos para contribuir a tus campañas de generación de demanda.",
                "plataforma-venoot" => "Algunos eventos que ya se han publicado mediante nuestro sistema.",
                "clientes" => "Nuestros Clientes",
                "morethan" => "+ de",
                "enviados" => "eMails enviados",
                "check" => "Check-in de asistentes",
                "usuarios" => "Usuarios promedio conectados",
                "bcontacto" => "Envíanos tu información o llámanos para poder ayudarte y entregarte una asesoría de calidad!",
                "derechos" => "Todos los derechos reservados.",
                "contactosend" => "Quiero me contacten",
                "nombre" => "Ingresa tu nombre",
                "email" => "Ingresa tu email",
                "valido" => "Ingresa un dato valido",
                "loginuser" => "Login Usuarios",
                "loginparticipant" => "Login Participantes",
            )
        ];

        return view('static-index', ['lang' => $lang[$locale]]);
    }

    public function fallback()
    {
        return view('app');
    }
}
