branch-defaults:
  staging:
    environment: Venoot-stage
environment-defaults:
  Venoot-stage:
    branch: null
    repository: null
global:
  application_name: Venoot
  default_ec2_keyname: Venoot
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.2 running on
    64bit Amazon Linux/2.9.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
